# docker-compose.yml

version: '3.8' # 使用一个较新的版本

services:
  # 服务名称，可以自定义，这里我们叫它 db
  nextjs-postgres-app:
    # 指定要使用的 Docker 镜像
    # postgres:16 表示使用官方的 PostgreSQL 16 版本镜像
    image: postgres:16

    # 为了防止容器重启后数据丢失，我们将数据持久化到本地
    volumes:
      - postgres-data:/var/lib/postgresql/data

    # 设置容器的环境变量，用于初始化数据库
    environment:
      POSTGRES_USER: root            # 设置数据库用户名
      POSTGRES_PASSWORD: 123456 # 设置数据库密码
      POSTGRES_DB: nextjs_app        # 设置要创建的数据库名称

    # 将容器的 5432 端口（PostgreSQL 默认端口）映射到你主机的 5432 端口
    # 如果你本地的 5432 端口已被占用，可以改成 "5433:5432"
    ports:
      - "5432:5432"

    # 强制容器在开发模式下总是重启，除非手动停止
    restart: always

# 定义一个具名的数据卷，用于持久化存储数据库数据
volumes:
  postgres-data:
